#undef __Q_ADD
#undef Q_INIT_FN
#undef Q_IS_FULL_FN
#undef Q_IS_EMPTY_FN
#undef Q_ENQUEUE_FN
#undef Q_DEQUEUE_FN
#undef Q_SIZE_FN
#undef Q_FREE_FN
#undef Q_CONTAINS_FN
#undef QUEUE_CAPACITY
#undef QUEUE_TYPE
#undef QUEUE_TYPENAME
#undef QUEUE_DONT_UNDEF
