#include "i2c.h"

// =====================
// Configuration macros
// =====================

#define I2C_TIMEOUT_MS  10U   // Simple timeout for waits (tune as needed)

// You were already using this timing value; we'll keep it.
// It’s usually generated by ST’s timing tool for 100 kHz or 400 kHz.
#define I2C_TIMING_REG  0x30420F13U

// =====================
// Internal helpers
// =====================

/*
 * Simple timeout helper: wait until (ISR & flag_mask) != 0 or timeout.
 * Returns true if flag became set, false on timeout.
 */
static bool i2c_wait_flag_set(I2C_TypeDef* i2c, uint32_t flag_mask)
{
    uint32_t start = (uint32_t)ms_since_start();
    while ((i2c->ISR & flag_mask) == 0U) {
        if (((uint32_t)ms_since_start() - start) > I2C_TIMEOUT_MS) {
            return false;
        }
    }
    return true;
}

/*
 * Similarly, wait until (ISR & flag_mask) == 0 or timeout.
 */
static bool i2c_wait_flag_clear(I2C_TypeDef* i2c, uint32_t flag_mask)
{
    uint32_t start = (uint32_t)ms_since_start();
    while ((i2c->ISR & flag_mask) != 0U) {
        if (((uint32_t)ms_since_start() - start) > I2C_TIMEOUT_MS) {
            return false;
        }
    }
    return true;
}

/*
 * Clear common I2C error/stop flags before starting a new transfer.
 */
static void i2c_clear_errors_and_stop(I2C_TypeDef* i2c)
{
    i2c->ICR = I2C_ICR_STOPCF    // Clear STOPF
             | I2C_ICR_NACKCF    // Clear NACKF
             | I2C_ICR_BERRCF    // Clear BERR
             | I2C_ICR_ARLOCF;   // Clear ARLO
}

/*
 * Return INVALID_I2C if any serious error flag is set.
 * You can expand this to more specific error codes if your I2C_Error enum supports it.
 */
static I2C_Error i2c_check_errors(I2C_TypeDef* i2c)
{
    uint32_t isr = i2c->ISR;

    if (isr & (I2C_ISR_BERR | I2C_ISR_ARLO | I2C_ISR_NACKF)) {
        // Clear them for next time
        i2c_clear_errors_and_stop(i2c);
        return INVALID_I2C;
    }

    return I2C_OK;
}

// =====================
// Public API
// =====================

void i2c_init(void)
{
    // Enable GPIOB clock (for PB8-11)
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;

    // -------- GPIO config for I2C1 (PB8=SCL, PB9=SDA) and I2C2 (PB10=SCL, PB11=SDA) --------

    // Clear mode bits for PB8,9,10,11
    GPIOB->MODER &=
        ~(GPIO_MODER_MODE8_Msk | GPIO_MODER_MODE9_Msk |
          GPIO_MODER_MODE10_Msk | GPIO_MODER_MODE11_Msk);

    // Set mode = 10b (Alternate function) for PB8-11
    GPIOB->MODER |= (2U << GPIO_MODER_MODE8_Pos)
                  | (2U << GPIO_MODER_MODE9_Pos)
                  | (2U << GPIO_MODER_MODE10_Pos)
                  | (2U << GPIO_MODER_MODE11_Pos);

    // Optional: set as open-drain, high speed, with pull-ups as needed
    GPIOB->OTYPER |= GPIO_OTYPER_OT8 | GPIO_OTYPER_OT9
                   | GPIO_OTYPER_OT10 | GPIO_OTYPER_OT11;

    GPIOB->OSPEEDR |= (3U << GPIO_OSPEEDR_OSPEED8_Pos)
                    | (3U << GPIO_OSPEEDR_OSPEED9_Pos)
                    | (3U << GPIO_OSPEEDR_OSPEED10_Pos)
                    | (3U << GPIO_OSPEEDR_OSPEED11_Pos);

    // If you have external pull-ups on the I2C lines, you can leave PUPDR = 0.
    // Otherwise, enable pull-ups:
    // GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD8_Msk | GPIO_PUPDR_PUPD9_Msk |
    //                   GPIO_PUPDR_PUPD10_Msk | GPIO_PUPDR_PUPD11_Msk);
    // GPIOB->PUPDR |= (1U << GPIO_PUPDR_PUPD8_Pos)  // PB8 pull-up
    //               | (1U << GPIO_PUPDR_PUPD9_Pos)  // PB9 pull-up
    //               | (1U << GPIO_PUPDR_PUPD10_Pos) // PB10 pull-up
    //               | (1U << GPIO_PUPDR_PUPD11_Pos);// PB11 pull-up

    // Set AF4 for PB8-11 (I2C1/I2C2)
    GPIOB->AFR[1] &= ~(GPIO_AFRH_AFSEL8_Msk | GPIO_AFRH_AFSEL9_Msk |
                       GPIO_AFRH_AFSEL10_Msk | GPIO_AFRH_AFSEL11_Msk);
    GPIOB->AFR[1] |= (4U << GPIO_AFRH_AFSEL8_Pos)
                   | (4U << GPIO_AFRH_AFSEL9_Pos)
                   | (4U << GPIO_AFRH_AFSEL10_Pos)
                   | (4U << GPIO_AFRH_AFSEL11_Pos);

    // -------- I2C peripheral config --------

    // Disable I2C1 and I2C2 before configuring
    I2C1->CR1 &= ~I2C_CR1_PE;
    I2C2->CR1 &= ~I2C_CR1_PE;

    // Enable APB1 clock for I2C1 and I2C2
    RCC->APB1ENR1 |= RCC_APB1ENR1_I2C1EN;
    RCC->APB1ENR1 |= RCC_APB1ENR1_I2C2EN;

    // Configure timing register for both I2C1 and I2C2
    I2C1->TIMINGR = I2C_TIMING_REG;
    I2C2->TIMINGR = I2C_TIMING_REG;

    // (Optional) enable analog filter / disable digital filter if needed
    // I2C1->CR1 &= ~I2C_CR1_DNF;
    // I2C1->CR1 |= I2C_CR1_ANFOFF; // or clear to enable analog filter depending on needs
    // Same for I2C2...

    // Enable I2C1 and I2C2
    I2C1->CR1 |= I2C_CR1_PE;
    I2C2->CR1 |= I2C_CR1_PE;
}

// ---------------------
// Blocking write
// ---------------------

I2C_Error i2c_write(I2C_TypeDef* i2c,
                    uint8_t slave_addr,
                    const uint8_t* data,
                    uint8_t data_len)
{
    if (data_len == 0U) {
        return I2C_OK;  // Nothing to send
    }

    // Wait until bus is free (BUSY cleared)
    if (!i2c_wait_flag_clear(i2c, I2C_ISR_BUSY)) {
        return INVALID_I2C;
    }

    // Clear errors and STOP from previous transfers
    i2c_clear_errors_and_stop(i2c);

    // Configure CR2 for this write:
    //  - 7-bit address in SADD
    //  - NBYTES = data_len
    //  - RD_WRN = 0 (write)
    //  - START = 1
    //  - AUTOEND = 1 (send STOP automatically after NBYTES)
    uint32_t cr2 = 0;
    cr2 |= ((uint32_t)slave_addr << I2C_CR2_SADD_Pos);   // 7-bit address
    cr2 |= ((uint32_t)data_len  << I2C_CR2_NBYTES_Pos);  // NBYTES
    cr2 |= I2C_CR2_START;                                // generate START
    cr2 |= I2C_CR2_AUTOEND;                              // auto STOP after last byte
    // RD_WRN is 0 by default (write)
    i2c->CR2 = cr2;

    // Send each byte
    for (uint8_t i = 0; i < data_len; i++) {
        // Wait for TXIS (Transmit Interrupt Status: TXDR is empty and ready)
        while ((i2c->ISR & I2C_ISR_TXIS) == 0U) {
            // If a NACK or bus error occurs, bail out
            I2C_Error err = i2c_check_errors(i2c);
            if (err != I2C_OK) {
                return err;
            }
            // Optional: timeout is already enforced by i2c_check_errors via ICR.
        }

        // Write next byte into TXDR
        i2c->TXDR = data[i] & 0xFFU;
    }

    // After last byte, AUTOEND will generate STOP.
    // Wait for STOPF to know the transfer is complete.
    if (!i2c_wait_flag_set(i2c, I2C_ISR_STOPF)) {
        return INVALID_I2C;
    }

    // Clear STOP flag for next transfer
    i2c->ICR = I2C_ICR_STOPCF;

    return I2C_OK;
}

// ---------------------
// Blocking read
// ---------------------

I2C_Error i2c_read(I2C_TypeDef* i2c,
                   uint8_t slave_addr,
                   uint8_t* data,
                   uint8_t data_len)
{
    if (data_len == 0U) {
        return I2C_OK;  // Nothing to read
    }

    // Wait until bus is free
    if (!i2c_wait_flag_clear(i2c, I2C_ISR_BUSY)) {
        return INVALID_I2C;
    }

    // Clear previous errors and STOP
    i2c_clear_errors_and_stop(i2c);

    // Configure CR2 for this read:
    //  - 7-bit address
    //  - NBYTES = data_len
    //  - RD_WRN = 1 (read)
    //  - START = 1
    //  - AUTOEND = 1
    uint32_t cr2 = 0;
    cr2 |= ((uint32_t)slave_addr << I2C_CR2_SADD_Pos);
    cr2 |= ((uint32_t)data_len  << I2C_CR2_NBYTES_Pos);
    cr2 |= I2C_CR2_START;
    cr2 |= I2C_CR2_AUTOEND;
    cr2 |= I2C_CR2_RD_WRN;   // read direction
    i2c->CR2 = cr2;

    // Receive each byte
    for (uint8_t i = 0; i < data_len; i++) {
        // Wait until RXNE (Receive buffer not empty)
        while ((i2c->ISR & I2C_ISR_RXNE) == 0U) {
            I2C_Error err = i2c_check_errors(i2c);
            if (err != I2C_OK) {
                return err;
            }
        }

        // Read a byte from RXDR
        data[i] = (uint8_t)(i2c->RXDR & 0xFFU);
    }

    // Wait for STOPF after the last byte
    if (!i2c_wait_flag_set(i2c, I2C_ISR_STOPF)) {
        return INVALID_I2C;
    }

    // Clear STOP flag
    i2c->ICR = I2C_ICR_STOPCF;

    return I2C_OK;
}

// ---------------------
// Register helpers
// ---------------------

I2C_Error i2c_write_reg(I2C_TypeDef* i2c,
                        uint8_t slave_addr,
                        uint8_t reg_addr,
                        const uint8_t* data,
                        uint8_t data_len)
{
    // We send: [reg_addr, data[0], data[1], ...]
    uint8_t buf_len = data_len + 1U;
    uint8_t buf[16];  // adjust size if needed; small stack buffer for typical cases

    if (buf_len > sizeof(buf)) {
        // For very large writes, you might want to allocate differently.
        return INVALID_I2C;
    }

    buf[0] = reg_addr;
    for (uint8_t i = 0; i < data_len; i++) {
        buf[i + 1U] = data[i];
    }

    return i2c_write(i2c, slave_addr, buf, buf_len);
}

I2C_Error i2c_read_reg(I2C_TypeDef* i2c,
                       uint8_t slave_addr,
                       uint8_t reg_addr,
                       uint8_t* data,
                       uint8_t data_len)
{
    I2C_Error err;

    // First, write the register address (1-byte write)
    err = i2c_write(i2c, slave_addr, &reg_addr, 1U);
    if (err != I2C_OK) {
        return err;
    }

    // Then read from that register.
    return i2c_read(i2c, slave_addr, data, data_len);
}
